### ISSUE TITLE
Can you provide me with the complete source code for audio preprocessing?

### ISSUE THREAD

**Issue by zxs94rfpy** [Jiaxin-Ye/TIM-Net_SER#12]
I am a graduate student of Changsha University of Science and Technology who studies synthetic speech detection. The features I extracted using your read.md audio preprocessing code are not as good as those you shared. Can you provide me with the complete source code for audio preprocessing? Thank you very much.

**Comment by OhadCohen97** [comment]
It will also great if the author can share the t-SNE code that used in the papar.

Thanks!

**Comment by Jiaxin-Ye** [comment]
Dear @zxs94rfpy and @OhadCohen97 ,

Thank you for your interest in this project and your valuable suggestions. I sincerely apologize for any inconvenience caused to you. We have taken notice of issues regarding the inability to reproduce MFCC features and we have uploaded the code of feature extraction. Moreover, in order to ensure result reproducibility, we have made tests shown in the figure below and found that: *i)* we reproduced the features using the same speech signals and code on the same device (i.e., device 1), and the extracted features closely match the ones we had provided which just have a difference in some digits after the decimal point; *ii)* we also reproduced them on different devices (i.e., device 1 and device 2), there are larger discrepancies between them. Specifically, the device 1 is based on arm64 CPU architecture with Darwin 22.6.0 kernel version, and the device 2 is based on x86_64 CPU architecture with Linux 4.15.0-76-generic kernel version. We provided the MFCC feature files utilized in the experiments to ensure reproducibility. You can use these files to avoid variations in feature extraction across different devices. The updated README file provides further details on the experiment specifics. Feel free to refer to it for more information.

<img width="571" alt="feature_preprocessing" src="https://github.com/Jiaxin-Ye/TIM-Net_SER/assets/55079122/b5c1b38c-8031-4103-9bba-9ebd7b0cce43">


I greatly appreciate your feedback, which helps us continually refine and enhance the quality of our work. If you have any further questions or feedback, please don't hesitate to reach out to me. Thank you very much for your understanding and support.

Best regards,

Jiaxin Ye
